<?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	$arParams['TARIFS_LINK_ELEMENTS_TEMPLATE'],
	array(
		"IBLOCK_TYPE" => "aspro_priority_catalog",
		"IBLOCK_ID" => $arParams['TARIFS_IBLOCK_ID'],
		"COUNT_SHOW_PROPRERTIES" => $arParams['COUNT_SHOW_PROPRERTIES'],
		"NEWS_COUNT" => $arParams['COUNT_TARIFS'],
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ID",
		"SORT_ORDER2" => "DESC",
		"FILTER_NAME" => "arrTarifsFilter",
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		),
		"PROPERTY_CODE" => $arParams["TARIFS_PROPERTY_CODE"],
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"VIEW_TYPE" => "list",
		"IMAGE_POSITION" => "left",
		"COUNT_IN_LINE" => "3",
		"COUNT_LG" => $arParams["COUNT_LG"],
		"COUNT_MD" => $arParams["COUNT_MD"],
		"COUNT_SM" => $arParams["COUNT_SM"],
		"COUNT_XS" => $arParams["COUNT_XS"],
		"SHOW_PROPS_NAME" => $arParams["SHOW_PROPS_NAME"],
		"ORDER_VIEW" => $bOrderViewBasket,
		"T_TARIF" => ($arParams["T_TARIF"] ? $arParams["T_TARIF"] : GetMessage("T_TARIF")),
		"S_ORDER_PRODUCT" => $arParams["S_ORDER_SERVISE"],
		"AJAX_OPTION_ADDITIONAL" => ""
	),
	false, array("HIDE_ICONS" => "Y")
);?>