<?define("STATISTIC_SKIP_ACTIVITY_CHECK", "true");?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");

if(!CModule::IncludeModule("sale") || !CModule::IncludeModule("catalog") || !CModule::IncludeModule("iblock")){
    echo "failure";
    return;
}

\Bitrix\Main\Loader::IncludeModule('aspro.next');

if($_REQUEST['propid']!="undefined") {
    $IBLOCK_ID = 17;
    $IBLOCK_TYPE_ID = 'aspro_next_catalog';
    global $filter;
    $filter['=PROPERTY_TYPE_PRODUCT'] = $_REQUEST['propid'];
    $APPLICATION->IncludeComponent(
        "bitrix:catalog.section",
        "catalog_custom_block_new_list",
        Array(
            "ACTION_VARIABLE" => "action",
            "ADD_DETAIL_TO_SLIDER" => "N",
            "ADD_ELEMENT_CHAIN" => "N",
            "ADD_PICT_PROP" => "MORE_PHOTO",
            "ADD_PROPERTIES_TO_BASKET" => "Y",
            "ADD_SECTIONS_CHAIN" => "Y",
            "ADD_TO_BASKET_ACTION" => array("BUY"),
            "ADD_TO_BASKET_ACTION_PRIMARY" => array("BUY"),
            "BACKGROUND_IMAGE" => "-",
            "BASKET_URL" => "/personal/basket.php",
            "BLOG_USE" => "N",
            "BRAND_PROPERTY" => "BRAND_REF",
            "BRAND_PROP_CODE" => array("BRAND_REF",""),
            "BRAND_USE" => "N",
            "BROWSER_TITLE" => "-",
            "CACHE_GROUPS" => "Y",
            "CACHE_TIME" => "36000000",
            "CACHE_TYPE" => "N",
            "CHECK_SECTION_ID_VARIABLE" => "N",
            "COMPARE_PATH" => "",
            "COMPATIBLE_MODE" => "Y",
            "COMPOSITE_FRAME_MODE" => "A",
            "COMPOSITE_FRAME_TYPE" => "AUTO",
            "CONVERT_CURRENCY" => "Y",
            "CURRENCY_ID" => "RUB",
            "DATA_LAYER_NAME" => "dataLayer",
            "DETAIL_PICTURE_MODE" => array("POPUP","MAGNIFIER"),
            "DETAIL_URL" => "",
            "DISABLE_INIT_JS_IN_COMPONENT" => "N",
            "DISCOUNT_PERCENT_POSITION" => "bottom-right",
            "DISPLAY_COMPARE" => "N",
            "DISPLAY_NAME" => "Y",
            "DISPLAY_PREVIEW_TEXT_MODE" => "E",
            "FB_USE" => "N",
            "FILE_404" => "",
            "GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
            "GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
            "PAGE_ELEMENT_COUNT" => "10",
            "DISPLAY_BOTTOM_PAGER" => "N",
            "GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
            "GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
            "GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "3",
            "GIFTS_MESS_BTN_BUY" => "Выбрать",
            "GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
            "GIFTS_SHOW_IMAGE" => "Y",
            "GIFTS_SHOW_NAME" => "Y",
            "GIFTS_SHOW_OLD_PRICE" => "Y",
            "HIDE_NOT_AVAILABLE_OFFERS" => "N",
            "IBLOCK_ID" => $IBLOCK_ID,
            "IBLOCK_TYPE" => $IBLOCK_TYPE_ID,
            "LABEL_PROP" => array("NEWPRODUCT"),
            "LABEL_PROP_MOBILE" => array(),
            "LABEL_PROP_POSITION" => "top-left",
            "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
            "LINK_IBLOCK_ID" => "",
            "LINK_IBLOCK_TYPE" => "",
            "LINK_PROPERTY_SID" => "",
            "MAIN_BLOCK_OFFERS_PROPERTY_CODE" => array("COLOR_REF"),
            "MAIN_BLOCK_PROPERTY_CODE" => array("MATERIAL"),
            "FILTER_NAME" => "filter",
            "MESS_BTN_ADD_TO_BASKET" => "В корзину",
            "MESS_BTN_BUY" => "Купить",
            "MESS_BTN_COMPARE" => "Сравнить",
            "MESS_BTN_SUBSCRIBE" => "Подписаться",
            "MESS_COMMENTS_TAB" => "Комментарии",
            "MESS_DESCRIPTION_TAB" => "Описание",
            "MESS_NOT_AVAILABLE" => "Нет в наличии",
            "MESS_PROPERTIES_TAB" => "Характеристики",
            "MESS_RELATIVE_QUANTITY_FEW" => "мало",
            "MESS_RELATIVE_QUANTITY_MANY" => "много",
            "MESS_SHOW_MAX_QUANTITY" => "Наличие",
            "META_DESCRIPTION" => "-",
            "META_KEYWORDS" => "-",
            "OFFERS_CART_PROPERTIES" => array("COLOR_REF"),
            "OFFERS_FIELD_CODE" => array("NAME","PREVIEW_PICTURE","DETAIL_PICTURE","DETAIL_PAGE_URL",""),
            "OFFERS_LIMIT" => "0",
            "OFFERS_PROPERTY_CODE" => array("ARTICLE","COLOR_REF","TEXTURE","IS_3DVIEW","MORE_PHOTO","FILES","FRAROMA","SPORT","VLAGOOTVOD","AGE","RUKAV","KAPUSHON","FRCOLLECTION","FRLINE","FRFITIL","FRMADEIN","FRELITE","TALL","FRFAMILY","FRSOSTAVCANDLE","FRTYPE","FRFORM",""),
            "OFFERS_SORT_FIELD" => "sort",
            "OFFERS_SORT_FIELD2" => "id",
            "OFFERS_SORT_ORDER" => "asc",
            "OFFERS_SORT_ORDER2" => "desc",
            "OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
            "OFFER_TREE_PROPS" => array("COLOR_REF","SIZES_SHOES","SIZES_CLOTHES"),
            "PARTIAL_PRODUCT_PROPERTIES" => "Y",
            "PRICE_CODE" => array("BASE","ИМ: Рек. розн. 0%"),
            "PRICE_VAT_INCLUDE" => "Y",
            "PRICE_VAT_SHOW_VALUE" => "N",
            "PRODUCT_ID_VARIABLE" => "id",
            "PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
            "PRODUCT_PAY_BLOCK_ORDER" => "rating,price,quantityLimit,quantity,buttons",
            "PRODUCT_PROPERTIES" => array(),
            "PRODUCT_PROPS_VARIABLE" => "prop",
            "PRODUCT_QUANTITY_VARIABLE" => "",
            "PRODUCT_SUBSCRIPTION" => "Y",
            "PROPERTY_CODE" => array(
                0 => "BRAND",
                1 => "CML2_ARTICLE",
                2 => "COLOR_REF2",
                3 => "PROP_159",
                4 => "PROP_2033",
                5 => "PROP_2049",
                6 => "PROP_2065",
                7 => "PROP_2052",
                8 => "PROP_2027",
                9 => "PROP_2053",
                10 => "PROP_2083",
                11 => "PROP_2026",
                12 => "PROP_2044",
                13 => "PROP_162",
                14 => "PROP_2054",
                15 => "PROP_2017",
                16 => "PROP_2055",
                17 => "PROP_2069",
                18 => "PROP_2062",
                19 => "PROP_2061",
                20 => "CML2_LINK",),
            "RELATIVE_QUANTITY_FACTOR" => "5",
            "SECTION_CODE" => "",
            "SECTION_CODE_PATH" => "",
            "SECTION_ID" => $_REQUEST['sectionid'],
            "INCLUDE_SUBSECTIONS" => "Y",
            "SECTION_URL" => "",
            "SEF_MODE" => "N",
            "SEF_RULE" => "",
            "SET_BROWSER_TITLE" => "Y",
            "SET_CANONICAL_URL" => "N",
            "SET_LAST_MODIFIED" => "N",
            "SET_META_DESCRIPTION" => "Y",
            "SET_META_KEYWORDS" => "Y",
            "SET_STATUS_404" => "N",
            "SET_TITLE" => "Y",
            "SET_VIEWED_IN_COMPONENT" => "N",
            "SHOW_404" => "N",
            "SHOW_CLOSE_POPUP" => "N",
            "SHOW_DEACTIVATED" => "N",
            "SHOW_DISCOUNT_PERCENT" => "Y",
            "SHOW_MAX_QUANTITY" => "M",
            "SHOW_OLD_PRICE" => "N",
            "SHOW_PRICE_COUNT" => "1",
            "SHOW_SLIDER" => "Y",
            "SLIDER_INTERVAL" => "5000",
            "SLIDER_PROGRESS" => "N",
            "STRICT_SECTION_CHECK" => "N",
            "TEMPLATE_THEME" => "blue",
            "TYPE_SKU" => "TYPE_1",
            "USE_COMMENTS" => "Y",
            "USE_ELEMENT_COUNTER" => "Y",
            "USE_ENHANCED_ECOMMERCE" => "Y",
            "USE_GIFTS_DETAIL" => "Y",
            "USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
            "USE_MAIN_ELEMENT_SECTION" => "N",
            "USE_PRICE_COUNT" => "N",
            "USE_PRODUCT_QUANTITY" => "N",
            "USE_VOTE_RATING" => "Y",
            "VK_USE" => "N",
            "VOTE_DISPLAY_AS_RATING" => "rating",
            "IBLOCK_STOCK_ID" => "19",
        )
    );
}
elseif($_REQUEST['id']!="") {
    $IBLOCK_ID = 17;
    $IBLOCK_TYPE_ID = 'aspro_next_catalog';
    global $filter;
    $filter['=ID'] = $_REQUEST['id'];

    //x5 определение основного раздела
    $cache_dir = '/iblock/elems/';
    $obCache = \Bitrix\Main\Data\Cache::createInstance();
    if ($obCache->initCache(3600000, serialize(array($IBLOCK_ID)),$cache_dir)) {
        $sectionId = $obCache->getVars();
    } elseif ($obCache->startDataCache()) {
        $arSelect = Array("ID", "IBLOCK_SECTION_ID");
        $arFilter = Array("IBLOCK_ID"=>$IBLOCK_ID, "ACTIVE_DATE"=>"Y", "ACTIVE"=>"Y","ID"=>$_REQUEST['id']);
        $res = \CIBlockElement::GetList(Array(), $arFilter, false, false, $arSelect);
        $arElement = $res->Fetch();

        $sectionId = $arElement['IBLOCK_SECTION_ID'];
        global $CACHE_MANAGER;
        if (defined('BX_COMP_MANAGED_CACHE')) {
            $CACHE_MANAGER->StartTagCache($cache_dir);
            $CACHE_MANAGER->RegisterTag("iblock_id_" . $IBLOCK_ID);
            $CACHE_MANAGER->EndTagCache();
        }
        $obCache->endDataCache($sectionId);
    }
    ?>

    <?php
    $arTransferParams = array (
        'SHOW_ABSENT' => NULL,
        'HIDE_NOT_AVAILABLE_OFFERS' => 'N',
        'PRICE_CODE' =>
            array (
                0 => 'ИМ: Рек. розн. 0%',
            ),
        'OFFER_TREE_PROPS' =>
            array (
                0 => 'COLOR_REF',
                1 => 'SIZES',
            ),
        'CACHE_TIME' => '3600000',
        'CONVERT_CURRENCY' => 'Y',
        'CURRENCY_ID' => 'RUB',
        'OFFERS_SORT_FIELD' => 'sort',
        'OFFERS_SORT_ORDER' => 'desc',
        'OFFERS_SORT_FIELD2' => 'CATALOG_QUANTITY',
        'OFFERS_SORT_ORDER2' => 'asc',
        'LIST_OFFERS_LIMIT' => '20',
        'CACHE_GROUPS' => 'N',
        'LIST_OFFERS_PROPERTY_CODE' =>
            array(
                0 => 'ARTICLE',
                1 => 'COLOR_REF',
                2 => 'SIZES',
                3 => 'GABARITY',
                4 => 'VOLUME',
                5 => '',
            ),
        'SHOW_DISCOUNT_TIME' => 'Y',
        'SHOW_COUNTER_LIST' => 'Y',
        'PRICE_VAT_INCLUDE' => 'Y',
        'USE_PRICE_COUNT' => 'Y',
        'SHOW_MEASURE' => 'Y',
        'SHOW_OLD_PRICE' => 'Y',
        'SHOW_DISCOUNT_PERCENT' => 'Y',
        'SHOW_DISCOUNT_PERCENT_NUMBER' => 'Y',
        'USE_REGION' => 'Y',
        'STORES' =>
            array (
                0 => '1',
                1 => '3',
            ),
        'DEFAULT_COUNT' => '1',
        'BASKET_URL' => '/basket/',
        'OFFERS_CART_PROPERTIES' =>
            array (
            ),
        'PRODUCT_PROPERTIES' =>
            array(
            ),
        'PARTIAL_PRODUCT_PROPERTIES' => 'Y',
        'ADD_PROPERTIES_TO_BASKET' => 'Y',
        'SHOW_DISCOUNT_TIME_EACH_SKU' => 'Y',
        'SHOW_ARTICLE_SKU' => 'Y',
        'OFFER_ADD_PICT_PROP' => 'MORE_PHOTO',
        'PRODUCT_QUANTITY_VARIABLE' => 'quantity',
    );
    ?>

    <div class="js_wrapper_items" data-params='<?=str_replace('\'', '"', CUtil::PhpToJSObject($arTransferParams, false))?>'>
        <div class="block">
            <?
            $APPLICATION->IncludeComponent(
                "bitrix:catalog.section",
                "catalog_custom_block_new",
                Array(
                    "ACTION_VARIABLE" => "action",
                    "ADD_DETAIL_TO_SLIDER" => "N",
                    "ADD_ELEMENT_CHAIN" => "N",
                    "ADD_PICT_PROP" => "MORE_PHOTO",
                    "ADD_PROPERTIES_TO_BASKET" => "Y",
                    "ADD_SECTIONS_CHAIN" => "Y",
                    "ADD_TO_BASKET_ACTION" => array("BUY"),
                    "ADD_TO_BASKET_ACTION_PRIMARY" => array("BUY"),
                    "BACKGROUND_IMAGE" => "-",
                    "BASKET_URL" => "/personal/basket.php",
                    "BLOG_USE" => "N",
                    "BRAND_PROPERTY" => "BRAND_REF",
                    "BRAND_PROP_CODE" => array("BRAND_REF",""),
                    "BRAND_USE" => "N",
                    "BROWSER_TITLE" => "-",
                    "CACHE_GROUPS" => "Y",
                    "CACHE_TIME" => "36000000",
                    "CACHE_TYPE" => "N",
                    "CHECK_SECTION_ID_VARIABLE" => "N",
                    "COMPARE_PATH" => "",
                    "COMPATIBLE_MODE" => "Y",
                    "COMPOSITE_FRAME_MODE" => "A",
                    "COMPOSITE_FRAME_TYPE" => "AUTO",
                    "CONVERT_CURRENCY" => "Y",
                    "CURRENCY_ID" => "RUB",
                    "DATA_LAYER_NAME" => "dataLayer",
                    "DETAIL_PICTURE_MODE" => array("POPUP","MAGNIFIER"),
                    "DETAIL_URL" => "",
                    "DISABLE_INIT_JS_IN_COMPONENT" => "N",
                    "DISCOUNT_PERCENT_POSITION" => "bottom-right",
                    "DISPLAY_COMPARE" => "N",
                    "DISPLAY_NAME" => "Y",
                    "DISPLAY_PREVIEW_TEXT_MODE" => "E",
                    "FB_USE" => "N",
                    "FILE_404" => "",
                    "GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
                    "GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
                    "GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "3",
                    "GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
                    "GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
                    "GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
                    "GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "3",
                    "GIFTS_MESS_BTN_BUY" => "Выбрать",
                    "GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
                    "GIFTS_SHOW_IMAGE" => "Y",
                    "GIFTS_SHOW_NAME" => "Y",
                    "GIFTS_SHOW_OLD_PRICE" => "Y",
                    "HIDE_NOT_AVAILABLE_OFFERS" => "N",
                    "IBLOCK_ID" => $IBLOCK_ID,
                    "IBLOCK_TYPE" => $IBLOCK_TYPE_ID,
                    "LABEL_PROP" => array("NEWPRODUCT"),
                    "LABEL_PROP_MOBILE" => array(),
                    "LABEL_PROP_POSITION" => "top-left",
                    "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
                    "LINK_IBLOCK_ID" => "",
                    "LINK_IBLOCK_TYPE" => "",
                    "LINK_PROPERTY_SID" => "",
                    "MAIN_BLOCK_OFFERS_PROPERTY_CODE" => array("COLOR_REF"),
                    "MAIN_BLOCK_PROPERTY_CODE" => array("MATERIAL"),
                    "FILTER_NAME" => "filter",
                    "MESS_BTN_ADD_TO_BASKET" => "В корзину",
                    "MESS_BTN_BUY" => "Купить",
                    "MESS_BTN_COMPARE" => "Сравнить",
                    "MESS_BTN_SUBSCRIBE" => "Подписаться",
                    "MESS_COMMENTS_TAB" => "Комментарии",
                    "MESS_DESCRIPTION_TAB" => "Описание",
                    "MESS_NOT_AVAILABLE" => "Нет в наличии",
                    "MESS_PROPERTIES_TAB" => "Характеристики",
                    "MESS_RELATIVE_QUANTITY_FEW" => "мало",
                    "MESS_RELATIVE_QUANTITY_MANY" => "много",
                    "MESS_SHOW_MAX_QUANTITY" => "Наличие",
                    "META_DESCRIPTION" => "-",
                    "META_KEYWORDS" => "-",
                    "OFFERS_CART_PROPERTIES" => array("COLOR_REF"),
                    "OFFERS_FIELD_CODE" => array("NAME","PREVIEW_PICTURE","DETAIL_PICTURE","DETAIL_PAGE_URL",""),
                    "OFFERS_LIMIT" => "0",
                    "OFFERS_PROPERTY_CODE" => array("ARTICLE","COLOR_REF","TEXTURE","IS_3DVIEW","MORE_PHOTO","FILES","FRAROMA","SPORT","VLAGOOTVOD","AGE","RUKAV","KAPUSHON","FRCOLLECTION","FRLINE","FRFITIL","FRMADEIN","FRELITE","TALL","FRFAMILY","FRSOSTAVCANDLE","FRTYPE","FRFORM",""),
                    "OFFERS_SORT_FIELD" => "sort",
                    "OFFERS_SORT_FIELD2" => "id",
                    "OFFERS_SORT_ORDER" => "asc",
                    "OFFERS_SORT_ORDER2" => "desc",
                    "OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
                    "OFFER_TREE_PROPS" => array("COLOR_REF","SIZES_SHOES","SIZES_CLOTHES"),
                    "PARTIAL_PRODUCT_PROPERTIES" => "Y",
                    "PRICE_CODE" => array("BASE","ИМ: Рек. розн. 0%"),
                    "PRICE_VAT_INCLUDE" => "Y",
                    "PRICE_VAT_SHOW_VALUE" => "N",
                    "PRODUCT_ID_VARIABLE" => "id",
                    "PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
                    "PRODUCT_PAY_BLOCK_ORDER" => "rating,price,quantityLimit,quantity,buttons",
                    "PRODUCT_PROPERTIES" => array(),
                    "PRODUCT_PROPS_VARIABLE" => "prop",
                    "PRODUCT_QUANTITY_VARIABLE" => "",
                    "PRODUCT_SUBSCRIPTION" => "Y",
                    "PROPERTY_CODE" => array(
                        0 => "671",
                        1 => "672",
                        2 => "673",
                        3 => "674",
                        4 => "675",
                        5 => "676",
                        6 => "677",
                        7 => "678",
                        8 => "679",
                        9 => "680",
                        10 => "683",
                        11 => "684",
                        12 => "685",
                        13 => "686",
                        14 => "687",
                        15 => "688",
                        16 => "689",
                        17 => "690",
                        18 => "691",
                        19 => "BRAND",
                        20 => "TYPE_PRODUCT",
                        21 => "SERIES",
                        22 => "MODEL",
                        23 => "CML2_ARTICLE",
                        24 => "TEXTURE",
                        25 => "COUNTRY_OF_ORIGIN",
                        26 => "GARANTY",
                        27 => "CML2_ATTRIBUTES",
                        28 => "VIDEO_YOUTUBE",
                        29 => "VYSOTA_DO_PODLOKOTNIKOV_HEIGHT_PODLOKOTNIK3",
                        30 => "VYSOTA_MINIMALNAYA_HEIGHT_MIN3",
                        31 => "VYSOTA_SIDENIYA_HEIGHT_SIDENIYA3",
                        32 => "VYSOTA_SPINKI_HEIGHT_SPINKI3",
                        33 => "GLUBINA_MINIMALNAYA_DEPTH_MIN3",
                        34 => "GLUBINA_SIDENIYA_DEPTH_SIDENIYA3",
                        35 => "DVERI_DOORS",
                        36 => "DLINA_SM_LENGTH",
                        37 => "ZHESTKOST_HARDNESS",
                        38 => "KARKAS_KASKAS",
                        39 => "KLASS_MEBELI_MEBELCLASS",
                        40 => "KOLICHESTVO_MEST_V_SEKTSII_KOLVOMESTVSEKCII3",
                        41 => "KOLICHESTVO_UPAKOVOK_KOLVOUPAK3",
                        42 => "KOMPLEKT_KOMPLECT",
                        43 => "KONSTRUKTSIYA_CONSTRUCTION",
                        44 => "KRESTOVINA_CROSS",
                        45 => "KROMKA_RABOCHIKH_POVERKHNOSTEY_KROMKA",
                        46 => "MATERIAL_MATERIAL",
                        47 => "MATERIAL_PATTERN",
                        48 => "MATERIAL_NAPOLNENIYA_FILLING_MATERIAL",
                        49 => "MATERIAL_OBIVKI_MATERIAL_OBIVKI3",
                        50 => "MATERIAL_POKRYTIYA_COVER_MATERIAL",
                        51 => "MEKHANIZM_MEHANIZM3",
                        52 => "MEKHANIZM_KACHANIYA_MEHANIZM_KACHANIYA3",
                        53 => "MEKHANIZMY_TILT",
                        54 => "NAGRUZKA_NAGRUZKA",
                        55 => "NAPOLNITELI_NAPOLNITELI",
                        56 => "NAPRAVLYAYUSHCHIE_MDIRECTIONS",
                        57 => "OBEM_TOVARA_OBYEM3",
                        58 => "OPORY_OPORY",
                        59 => "PODGOLOVNIK_PODGOLOVNIK3",
                        60 => "PODLOKOTNIKI_ARMRESTS",
                        61 => "PODLOKOTNIKI_PODLOKOTNIK3",
                        62 => "POLKA_POLKA",
                        63 => "POTREBLYAEMAYA_MOSHCHNOST_MOSCHNOST",
                        64 => "POYASNICHNYY_UPOR_LUMBAR_SUPPORT3",
                        65 => "RABOCHIE_POVERKHNOSTI_R_POVERHNOST",
                        66 => "REGULIROVKA_VYSOTY_SIDENIYA_REGUL_VYSOTY_SIDEN3",
                        67 => "REGULIROVKI_REGULATOR",
                        68 => "ROLIKI_ROLIKI3",
                        69 => "ROLIKI_SKATES",
                        70 => "SETKA_V_SPINKE_SETKAVSPINKE3",
                        71 => "SIDENE_SIDENIE",
                        72 => "SOEDINITELNAYA_FURNITURA_SOED_FURNITURA",
                        73 => "STOLESHNITSA_STOLESHNICA",
                        74 => "TIP_BAZY_TYPE_BASE3",
                        75 => "TIP_LAMPY_LAMPA_TYPE",
                        76 => "TOLSHCHINA_THICKNESS",
                        77 => "FASAD_FACADE",
                        78 => "SHIRINA_SIDENIYA_WIDTH_SIDENIYA3",
                        79 => "YASHCHIKI_BOXES",
                        80 => "MATERIAL_OBIVKI_SPINKI_KRESLA",
                        81 => "MATERIAL_OBIVKI_SIDENIYA_KRESLA",
                        82 => "SIZES",
                        83 => "PROP_159",
                        84 => "WIDHT",
                        85 => "DEPTH",
                        86 => "HEIGHT",
                        87 => "SHIRINAUPAK",
                        88 => "VYSOTAUPAK",
                        89 => "GLUBINAUPAK",
                        90 => "GABARITYUPAK",
                        91 => "BRUTTO",
                        92 => "VOLUME",
                        93 => "MATERIAL_PETEL",
                        94 => "AMORTIZATORY_PETEL",
                        95 => "MATERIAL_RUCHEK",
                        96 => "DOVODCHIK",
                        97 => "MATERIAL_KARKASA",
                        98 => "TEXTURE_KARKASA",
                        99 => "THICKNESS_KARKAS",
                        100 => "MATERIAL_ZADNEJ_STENKI_KARKASA",
                        101 => "TOLSHCHINA_ZADNEJ_STENKI_KARKASA",
                        102 => "TIP_DVEREJ",
                        103 => "MATERIAL_DVEREJ",
                        104 => "TEKSTURA_DVEREJ",
                        105 => "PROP_2033",
                        106 => "PROP_2049",
                        107 => "PROP_2065",
                        108 => "PROP_2052",
                        109 => "PROP_2027",
                        110 => "PROP_2053",
                        111 => "PROP_2083",
                        112 => "PROP_2026",
                        113 => "PROP_2044",
                        114 => "PROP_162",
                        115 => "PROP_2054",
                        116 => "PROP_2017",
                        117 => "PROP_2055",
                        118 => "PROP_2069",
                        119 => "PROP_2062",
                        120 => "PROP_2061",
                        121 => "RECOMMEND",
                        122 => "NEW",
                        123 => "STOCK",
                        124 => "VIDEO",
                        125 => "FILES",
                        126 => "",
                    ),
                    "RELATIVE_QUANTITY_FACTOR" => "5",
                    "SECTION_CODE" => "",
                    "SECTION_CODE_PATH" => "",
                    "SECTION_ID" => $sectionId,
                    "INCLUDE_SUBSECTIONS" => "Y",
                    "SECTION_URL" => "",
                    "SEF_MODE" => "N",
                    "SEF_RULE" => "",
                    "SET_BROWSER_TITLE" => "Y",
                    "SET_CANONICAL_URL" => "N",
                    "SET_LAST_MODIFIED" => "N",
                    "SET_META_DESCRIPTION" => "Y",
                    "SET_META_KEYWORDS" => "Y",
                    "SET_STATUS_404" => "N",
                    "SET_TITLE" => "Y",
                    "SET_VIEWED_IN_COMPONENT" => "N",
                    "SHOW_404" => "N",
                    "SHOW_CLOSE_POPUP" => "N",
                    "SHOW_DEACTIVATED" => "N",
                    "SHOW_DISCOUNT_PERCENT" => "Y",
                    "SHOW_DISCOUNT_PERCENT_NUMBER" => "Y",
                    "SHOW_MAX_QUANTITY" => "M",
                    "SHOW_OLD_PRICE" => "Y",
                    "SHOW_PRICE_COUNT" => "1",
                    "SHOW_SLIDER" => "Y",
                    "SLIDER_INTERVAL" => "5000",
                    "SLIDER_PROGRESS" => "N",
                    "STRICT_SECTION_CHECK" => "N",
                    "TEMPLATE_THEME" => "blue",
                    "TYPE_SKU" => "TYPE_1",
                    "USE_COMMENTS" => "Y",
                    "USE_ELEMENT_COUNTER" => "Y",
                    "USE_ENHANCED_ECOMMERCE" => "Y",
                    "USE_GIFTS_DETAIL" => "Y",
                    "USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
                    "USE_MAIN_ELEMENT_SECTION" => "N",
                    "USE_PRICE_COUNT" => "N",
                    "USE_PRODUCT_QUANTITY" => "N",
                    "USE_VOTE_RATING" => "Y",
                    "VK_USE" => "N",
                    "VOTE_DISPLAY_AS_RATING" => "rating",
                    "IBLOCK_STOCK_ID" => "19",
                )
            );
            ?>
        </div>
    </div>

    <?

    /*
        $APPLICATION->IncludeComponent(
            "bitrix:catalog.element",
            "ajax_view",
            Array(
                "ACTION_VARIABLE" => "action",
                "ADD_DETAIL_TO_SLIDER" => "N",
                "ADD_ELEMENT_CHAIN" => "N",
                "ADD_PICT_PROP" => "MORE_PHOTO",
                "ADD_PROPERTIES_TO_BASKET" => "Y",
                "ADD_SECTIONS_CHAIN" => "Y",
                "ADD_TO_BASKET_ACTION" => array("BUY"),
                "ADD_TO_BASKET_ACTION_PRIMARY" => array("BUY"),
                "BACKGROUND_IMAGE" => "-",
                "BASKET_URL" => "/personal/basket.php",
                "BLOG_USE" => "N",
                "BRAND_PROPERTY" => "BRAND_REF",
                "BRAND_PROP_CODE" => array("BRAND_REF",""),
                "BRAND_USE" => "N",
                "BROWSER_TITLE" => "-",
                "CACHE_GROUPS" => "Y",
                "CACHE_TIME" => "36000000",
                "CACHE_TYPE" => "N",
                "CHECK_SECTION_ID_VARIABLE" => "N",
                "COMPARE_PATH" => "",
                "COMPATIBLE_MODE" => "Y",
                "COMPOSITE_FRAME_MODE" => "A",
                "COMPOSITE_FRAME_TYPE" => "AUTO",
                "CONVERT_CURRENCY" => "Y",
                "CURRENCY_ID" => "RUB",
                "DATA_LAYER_NAME" => "dataLayer",
                "DETAIL_PICTURE_MODE" => array("POPUP","MAGNIFIER"),
                "DETAIL_URL" => "",
                "DISABLE_INIT_JS_IN_COMPONENT" => "N",
                "DISCOUNT_PERCENT_POSITION" => "bottom-right",
                "DISPLAY_COMPARE" => "N",
                "DISPLAY_NAME" => "Y",
                "DISPLAY_PREVIEW_TEXT_MODE" => "E",
                "ELEMENT_CODE" => "",
                "ELEMENT_ID" => $_REQUEST['id'],
                "FB_USE" => "N",
                "FILE_404" => "",
                "GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
                "GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
                "GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "3",
                "GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
                "GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
                "GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
                "GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "3",
                "GIFTS_MESS_BTN_BUY" => "Выбрать",
                "GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
                "GIFTS_SHOW_IMAGE" => "Y",
                "GIFTS_SHOW_NAME" => "Y",
                "GIFTS_SHOW_OLD_PRICE" => "Y",
                "HIDE_NOT_AVAILABLE_OFFERS" => "N",
                "IBLOCK_ID" => $IBLOCK_ID,
                "IBLOCK_TYPE" => $IBLOCK_TYPE_ID,
                "LABEL_PROP" => array("NEWPRODUCT"),
                "LABEL_PROP_MOBILE" => array(),
                "LABEL_PROP_POSITION" => "top-left",
                "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
                "LINK_IBLOCK_ID" => "",
                "LINK_IBLOCK_TYPE" => "",
                "LINK_PROPERTY_SID" => "",
                "MAIN_BLOCK_OFFERS_PROPERTY_CODE" => array("COLOR_REF"),
                "MAIN_BLOCK_PROPERTY_CODE" => array("MATERIAL"),
                "MESSAGE_404" => "",
                "MESS_BTN_ADD_TO_BASKET" => "В корзину",
                "MESS_BTN_BUY" => "Купить",
                "MESS_BTN_COMPARE" => "Сравнить",
                "MESS_BTN_SUBSCRIBE" => "Подписаться",
                "MESS_COMMENTS_TAB" => "Комментарии",
                "MESS_DESCRIPTION_TAB" => "Описание",
                "MESS_NOT_AVAILABLE" => "Нет в наличии",
                "MESS_PROPERTIES_TAB" => "Характеристики",
                "MESS_RELATIVE_QUANTITY_FEW" => "мало",
                "MESS_RELATIVE_QUANTITY_MANY" => "много",
                "MESS_SHOW_MAX_QUANTITY" => "Наличие",
                "META_DESCRIPTION" => "-",
                "META_KEYWORDS" => "-",
                "OFFERS_CART_PROPERTIES" => array("COLOR_REF"),
                "OFFERS_FIELD_CODE" => array("NAME","PREVIEW_PICTURE","DETAIL_PICTURE","DETAIL_PAGE_URL",""),
                "OFFERS_LIMIT" => "0",
                "OFFERS_PROPERTY_CODE" => array("ARTICLE","COLOR_REF","TEXTURE","IS_3DVIEW","MORE_PHOTO","FILES","FRAROMA","SPORT","VLAGOOTVOD","AGE","RUKAV","KAPUSHON","FRCOLLECTION","FRLINE","FRFITIL","FRMADEIN","FRELITE","TALL","FRFAMILY","FRSOSTAVCANDLE","FRTYPE","FRFORM",""),
                "OFFERS_SORT_FIELD" => "sort",
                "OFFERS_SORT_FIELD2" => "id",
                "OFFERS_SORT_ORDER" => "asc",
                "OFFERS_SORT_ORDER2" => "desc",
                "OFFER_ADD_PICT_PROP" => "MORE_PHOTO",
                "OFFER_TREE_PROPS" => array("COLOR_REF","SIZES_SHOES","SIZES_CLOTHES"),
                "PARTIAL_PRODUCT_PROPERTIES" => "Y",
                "PRICE_CODE" => array("BASE","ИМ: Рек. розн. 0%"),
                "PRICE_VAT_INCLUDE" => "Y",
                "PRICE_VAT_SHOW_VALUE" => "N",
                "PRODUCT_ID_VARIABLE" => "id",
                "PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
                "PRODUCT_PAY_BLOCK_ORDER" => "rating,price,quantityLimit,quantity,buttons",
                "PRODUCT_PROPERTIES" => array(),
                "PRODUCT_PROPS_VARIABLE" => "prop",
                "PRODUCT_QUANTITY_VARIABLE" => "",
                "PRODUCT_SUBSCRIPTION" => "Y",
                "PROPERTY_CODE" => array("BRAND","TYPE_PRODUCT","SERIES","MODEL","CML2_ARTICLE","TEXTURE","COUNTRY_OF_ORIGIN","GARANTY","CML2_ATTRIBUTES","SIZES","PROP_159","WIDHT","DEPTH","HEIGHT","PROP_2033","PROP_2049","PROP_2065","PROP_2052","PROP_2027","PROP_2053","PROP_2083","PROP_2026","PROP_2044","PROP_162","PROP_2054","PROP_2017","PROP_2055","PROP_2069","PROP_2062","PROP_2061",""),
                "RELATIVE_QUANTITY_FACTOR" => "5",
                "SECTION_CODE" => "",
                "SECTION_CODE_PATH" => "",
                "SECTION_ID" => "",
                "SECTION_ID_VARIABLE" => "SECTION_ID",
                "SECTION_URL" => "",
                "SEF_MODE" => "N",
                "SEF_RULE" => "",
                "SET_BROWSER_TITLE" => "Y",
                "SET_CANONICAL_URL" => "N",
                "SET_LAST_MODIFIED" => "N",
                "SET_META_DESCRIPTION" => "Y",
                "SET_META_KEYWORDS" => "Y",
                "SET_STATUS_404" => "N",
                "SET_TITLE" => "Y",
                "SET_VIEWED_IN_COMPONENT" => "N",
                "SHOW_404" => "N",
                "SHOW_CLOSE_POPUP" => "N",
                "SHOW_DEACTIVATED" => "N",
                "SHOW_DISCOUNT_PERCENT" => "Y",
                "SHOW_MAX_QUANTITY" => "M",
                "SHOW_OLD_PRICE" => "N",
                "SHOW_PRICE_COUNT" => "1",
                "SHOW_SLIDER" => "Y",
                "SLIDER_INTERVAL" => "5000",
                "SLIDER_PROGRESS" => "N",
                "STRICT_SECTION_CHECK" => "N",
                "TEMPLATE_THEME" => "blue",
                "TYPE_SKU" => "TYPE_1",
                "USE_COMMENTS" => "Y",
                "USE_ELEMENT_COUNTER" => "Y",
                "USE_ENHANCED_ECOMMERCE" => "Y",
                "USE_GIFTS_DETAIL" => "Y",
                "USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
                "USE_MAIN_ELEMENT_SECTION" => "N",
                "USE_PRICE_COUNT" => "N",
                "USE_PRODUCT_QUANTITY" => "N",
                "USE_VOTE_RATING" => "Y",
                "VK_USE" => "N",
                "VOTE_DISPLAY_AS_RATING" => "rating"
            )
        );
    */
}
else $errors[] = "Не задан id";

if($errors) print_r($errors);
?>